const musicData = [
  // =====================
  // 1. 기쁨 (Joy) - 신나고 에너지 넘치는 25곡
  // =====================
  { title: "Dynamite", artist: "BTS", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "gdZLi9oWNZg", desc: "전 세계를 강타한 경쾌하고 신나는 디스코 팝." },
  { title: "Uptown Funk", artist: "Mark Ronson (ft. Bruno Mars)", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "OPf0YbXqDm0", desc: "듣는 순간 몸을 움직이게 만드는 펑키한 리듬." },
  { title: "Happy", artist: "Pharrell Williams", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "y6Sxv-sUYtM", desc: "행복 바이러스를 전파하는 기분 좋은 팝송." },
  { title: "강남스타일", artist: "싸이 (PSY)", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "9bZkp7q19f0", desc: "전 세계가 춤추게 만든 레전드 신나는 곡." },
  { title: "Shake It Off", artist: "Taylor Swift", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "nfWlot6h_JM", desc: "스트레스를 털어버리고 신나게 춤추고 싶은 곡." },
  { title: "Can't Stop The Feeling!", artist: "Justin Timberlake", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "ru0K8uYEZWw", desc: "온몸에 전율이 흐르는 행복한 댄스곡." },
  { title: "Sugar", artist: "Maroon 5", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "09R8_2nJtjg", desc: "결혼식 축가로도 유명한 달콤하고 신나는 노래." },
  { title: "Cheer Up", artist: "TWICE", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "c7rCyll5AeY", desc: "듣기만 해도 힘이 나는 상큼한 응원가." },
  { title: "빨간 맛", artist: "Red Velvet", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "WyiIGEHQP8o", desc: "여름의 청량함이 가득 느껴지는 상큼한 곡." },
  { title: "마지막처럼", artist: "BLACKPINK", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "Amq-qlqbjYA", desc: "사랑에 빠진 설렘을 담은 신나는 댄스곡." },
  { title: "I AM", artist: "IVE", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "6ZUIwj3FgUY", desc: "벅차오르는 자신감을 주는 파워풀한 곡." },
  { title: "Hype Boy", artist: "NewJeans", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "11cta61wi0g", desc: "트렌디한 비트와 청량한 멜로디의 화제곡." },
  { title: "파이팅 해야지", artist: "부석순 (SEVENTEEN)", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "mBXBOLG06Wc", desc: "지친 일상에 에너지를 불어넣는 긍정송." },
  { title: "24K Magic", artist: "Bruno Mars", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "UqyT8IEBkvY", desc: "화려하고 럭셔리한 파티 분위기의 곡." },
  { title: "Viva La Vida", artist: "Coldplay", mood: "기쁨", genre: "Rock", lang: "en", youtubeId: "dvgZkm1xWPE", desc: "웅장한 사운드가 가슴을 뛰게 하는 명곡." },
  { title: "Dancing Queen", artist: "ABBA", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "xFrGuyw1V8s", desc: "세대를 초월해 사랑받는 디스코의 여왕." },
  { title: "아무노래", artist: "지코 (ZICO)", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "UuV2BmJ1p_I", desc: "편안하고 즐겁게 흥얼거릴 수 있는 힙합 곡." },
  { title: "라일락", artist: "아이유 (IU)", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "v7bnOxV4jAc", desc: "봄바람처럼 화사하고 기분 좋은 시티팝." },
  { title: "Dolphin", artist: "오마이걸", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "oaRTMjLdiDw", desc: "물보라를 일으키며 터질 듯한 상큼함." },
  { title: "I Feel It Coming", artist: "The Weeknd", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "qFLhGq0060w", desc: "세련된 레트로 감성이 돋보이는 기분 좋은 곡." },
  { title: "아이돌 (アイドル)", artist: "YOASOBI", mood: "기쁨", genre: "J-Pop", lang: "ja", youtubeId: "ZRtdQ81jPUQ", desc: "애니메이션 '최애의 아이' 주제곡, 폭발적 에너지." },
  { title: "코이 (恋)", artist: "호시노 겐", mood: "기쁨", genre: "J-Pop", lang: "ja", youtubeId: "jhOVibLEDhA", desc: "드라마 엔딩 댄스로 유명한 밝고 경쾌한 곡." },
  { title: "Love Lee", artist: "AKMU (악뮤)", mood: "기쁨", genre: "K-Pop", lang: "ko", youtubeId: "EIz09kLzN9k", desc: "사랑스러운 가사와 통통 튀는 멜로디." },
  { title: "The Lazy Song", artist: "Bruno Mars", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "fLexgOxsZu0", desc: "아무것도 안 하고 쉬고 싶은 날 듣는 즐거운 곡." },
  { title: "Roar", artist: "Katy Perry", mood: "기쁨", genre: "Pop", lang: "en", youtubeId: "CevxZvSJLk8", desc: "자신감을 충전해주는 파워풀한 팝송." },

  // =====================
  // 2. 슬픔 (Sadness) - 감성적이고 애절한 25곡
  // =====================
  { title: "Someone Like You", artist: "Adele", mood: "슬픔", genre: "Pop", lang: "en", youtubeId: "hLQl3WQQoQ0", desc: "이별의 아픔을 호소력 짙게 표현한 명곡." },
  { title: "Stay With Me", artist: "Sam Smith", mood: "슬픔", genre: "Pop", lang: "en", youtubeId: "pB-5XG-DbAA", desc: "외로움이 짙게 묻어나는 소울풀한 노래." },
  { title: "야생화", artist: "박효신", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "OxgiiyLp5pk", desc: "폭발적인 가창력으로 슬픔을 승화시킨 곡." },
  { title: "밤편지", artist: "아이유 (IU)", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "BzYnNdJhZQw", desc: "그리운 사람에게 보내는 차분한 편지 같은 곡." },
  { title: "Fine", artist: "태연 (TAEYEON)", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "NHXUM-6a3dU", desc: "이별 후 괜찮지 않은 마음을 솔직하게 부른 곡." },
  { title: "첫눈처럼 너에게 가겠다", artist: "에일리 (Ailee)", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "6rS7OUGXUik", desc: "도깨비 OST, 겨울마다 생각나는 애절한 발라드." },
  { title: "좋니", artist: "윤종신", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "b1kQvZhQ6_M", desc: "헤어진 연인의 행복을 빌어주지 못하는 현실적 가사." },
  { title: "All of Me", artist: "John Legend", mood: "슬픔", genre: "R&B", lang: "en", youtubeId: "450p7goxZqg", desc: "피아노 선율과 깊은 보이스가 마음을 울리는 곡." },
  { title: "Fix You", artist: "Coldplay", mood: "슬픔", genre: "Rock", lang: "en", youtubeId: "k4V3Mo61fJM", desc: "상처 입은 마음을 위로하고 치유해주는 노래." },
  { title: "Memories", artist: "Maroon 5", mood: "슬픔", genre: "Pop", lang: "en", youtubeId: "SlPhMPnQ58k", desc: "떠나간 소중한 사람들을 추억하는 곡." },
  { title: "Stay", artist: "BLACKPINK", mood: "슬픔", genre: "K-Pop", lang: "ko", youtubeId: "FzVR_fymZw4", desc: "떠나가는 연인을 붙잡고 싶은 애절한 마음." },
  { title: "Loser", artist: "BIGBANG", mood: "슬픔", genre: "K-Pop", lang: "ko", youtubeId: "1CTced9CMMk", desc: "외로움과 쓸쓸함을 담은 미디엄 템포 곡." },
  { title: "비도 오고 그래서", artist: "헤이즈 (Heize)", mood: "슬픔", genre: "R&B", lang: "ko", youtubeId: "afxLaQiLu-o", desc: "비 오는 날 헤어진 연인을 생각하는 노래." },
  { title: "한숨", artist: "이하이", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "5iSlfF8TQ9k", desc: "지친 하루의 끝에 깊은 위로를 건네는 노래." },
  { title: "너를 만나", artist: "폴킴", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "vnS_jn2uibs", desc: "사랑하는 사람을 만나 행복했던 기억을 담은 곡." },
  { title: "레몬 (Lemon)", artist: "요네즈 켄시", mood: "슬픔", genre: "J-Pop", lang: "ja", youtubeId: "SX_ViT4Ra7k", desc: "사랑하는 사람을 잃은 상실감을 노래한 명곡." },
  { title: "드라이 플라워 (ドライフラワー)", artist: "유우리 (Yuuri)", mood: "슬픔", genre: "J-Pop", lang: "ja", youtubeId: "kzZ6KXDM1RI", desc: "이별 후의 감정을 메마른 꽃에 비유한 노래." },
  { title: "Drivers License", artist: "Olivia Rodrigo", mood: "슬픔", genre: "Pop", lang: "en", youtubeId: "ZmDBbnmKpqQ", desc: "이별 후 혼자 운전하며 느끼는 공허함." },
  { title: "Someone You Loved", artist: "Lewis Capaldi", mood: "슬픔", genre: "Pop", lang: "en", youtubeId: "bCuhuePlP8o", desc: "사랑하는 사람을 떠나보낸 아픔을 노래한 곡." },
  { title: "Chandelier", artist: "Sia", mood: "슬픔", genre: "Pop", lang: "en", youtubeId: "2vjPBrBU-TM", desc: "파티 뒤에 찾아오는 공허함과 고통을 표현한 곡." },
  { title: "See You Again", artist: "Wiz Khalifa (ft. Charlie Puth)", mood: "슬픔", genre: "Hip-hop", lang: "en", youtubeId: "RgKAFK5djSk", desc: "떠나간 친구를 추모하며 다시 만날 날을 기약함." },
  { title: "Sofa", artist: "크러쉬 (Crush)", mood: "슬픔", genre: "R&B", lang: "ko", youtubeId: "Ianq_1GDzbE", desc: "빈 소파에 남겨진 이별의 흔적을 노래함." },
  { title: "어떻게 이별까지 사랑하겠어, 널 사랑하는 거지", artist: "AKMU (악뮤)", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "mAKsZ26SabQ", desc: "이별까지 사랑하겠다는 성숙하고 슬픈 다짐." },
  { title: "어디에도", artist: "엠씨더맥스 (MC the Max)", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "va5rf20Un24", desc: "잊으려 해도 잊을 수 없는 사랑을 노래함." },
  { title: "You Are My Everything", artist: "거미 (Gummy)", mood: "슬픔", genre: "Ballad", lang: "ko", youtubeId: "ToASX6axGuw", desc: "태양의 후예 OST, 운명적인 사랑." },

  // =====================
  // 3. 평온 (Calm) - 편안하고 힐링되는 25곡
  // =====================
  { title: "Sunday Morning", artist: "Maroon 5", mood: "평온", genre: "Pop", lang: "en", youtubeId: "S2Cti12XBw4", desc: "일요일 아침 햇살처럼 포근하고 여유로운 곡." },
  { title: "Paris in the Rain", artist: "Lauv", mood: "평온", genre: "Pop", lang: "en", youtubeId: "kOCkne-Bku4", desc: "비 오는 파리 거리를 걷는 듯한 로맨틱한 무드." },
  { title: "Best Part", artist: "H.E.R. (Ft. Daniel Caesar)", mood: "평온", genre: "R&B", lang: "en", youtubeId: "75-Com9Bo_s", desc: "달콤하고 부드러운 목소리가 마음을 녹이는 곡." },
  { title: "Love Yourself", artist: "Justin Bieber", mood: "평온", genre: "Pop", lang: "en", youtubeId: "oyEuk8j8imI", desc: "어쿠스틱 기타 선율이 돋보이는 차분한 곡." },
  { title: "Perfect", artist: "Ed Sheeran", mood: "평온", genre: "Pop", lang: "en", youtubeId: "2Vv-BfVoq4g", desc: "완벽한 사랑을 노래하는 감미로운 발라드." },
  { title: "I'm Yours", artist: "Jason Mraz", mood: "평온", genre: "Pop", lang: "en", youtubeId: "EkHTsc9PU2A", desc: "듣기만 해도 기분 좋아지는 어쿠스틱 힐링 송." },
  { title: "Palette", artist: "아이유 (IU)", mood: "평온", genre: "K-Pop", lang: "ko", youtubeId: "d9IxdwEFk1c", desc: "스물다섯의 나를 차분하게 돌아보는 노래." },
  { title: "11:11", artist: "태연 (TAEYEON)", mood: "평온", genre: "Ballad", lang: "ko", youtubeId: "ulr0muQKjk0", desc: "늦은 밤 차분하게 듣기 좋은 어쿠스틱 기타 곡." },
  { title: "우주를 줄게", artist: "볼빨간사춘기", mood: "평온", genre: "K-Pop", lang: "ko", youtubeId: "9U8uA702xrE", desc: "사랑에 빠진 마음을 우주에 빗댄 예쁜 곡." },
  { title: "폰서트", artist: "10CM", mood: "평온", genre: "Folk", lang: "ko", youtubeId: "mOo8bVzN9M8", desc: "연인에게 불러주는 달콤한 전화 콘서트." },
  { title: "별 보러 가자", artist: "적재", mood: "평온", genre: "Ballad", lang: "ko", youtubeId: "hX1YVzdnpEc", desc: "밤하늘을 보며 산책하고 싶어지는 낭만적인 노래." },
  { title: "Beautiful", artist: "크러쉬 (Crush)", mood: "평온", genre: "Ballad", lang: "ko", youtubeId: "W0cs6ciCt_k", desc: "도깨비 OST, 따뜻하고 감미로운 멜로디." },
  { title: "Instagram", artist: "딘 (DEAN)", mood: "평온", genre: "R&B", lang: "ko", youtubeId: "wKyMIrBClYw", desc: "잠들기 전 침대에서 듣기 좋은 트렌디한 감성." },
  { title: "Square (2017)", artist: "백예린 (Yerin Baek)", mood: "평온", genre: "R&B", lang: "en", youtubeId: "4iFP_wd6QU8", desc: "세련된 음색과 몽환적인 분위기가 어우러진 명곡." },
  { title: "200%", artist: "AKMU (악뮤)", mood: "평온", genre: "K-Pop", lang: "ko", youtubeId: "0KSOMA3QBU0", desc: "상큼하고 기분 좋아지는 사랑 노래." },
  { title: "Day 1", artist: "HONNE", mood: "평온", genre: "Pop", lang: "en", youtubeId: "hWOB5QYcmh0", desc: "첫날부터 사랑에 빠졌다는 달콤한 고백." },
  { title: "At My Worst", artist: "Pink Sweat$", mood: "평온", genre: "R&B", lang: "en", youtubeId: "8CEJoCr_9UI", desc: "있는 그대로의 나를 사랑해달라는 따뜻한 노래." },
  { title: "Just The Way You Are", artist: "Bruno Mars", mood: "평온", genre: "Pop", lang: "en", youtubeId: "LjhCEhWiKXk", desc: "지금 모습 그대로 완벽하다는 찬사." },
  { title: "Don't Know Why", artist: "Norah Jones", mood: "평온", genre: "Jazz", lang: "en", youtubeId: "tO4dxvguQDk", desc: "나른한 오후에 듣기 좋은 부드러운 재즈." },
  { title: "Let It Be", artist: "The Beatles", mood: "평온", genre: "Rock", lang: "en", youtubeId: "QDYfEBY9NM4", desc: "마음의 평화를 주는 전설적인 명곡." },
  { title: "제주도의 푸른 밤", artist: "태연 (TAEYEON)", mood: "평온", genre: "Ballad", lang: "ko", youtubeId: "hSPcExVhquE", desc: "제주도의 여유로움이 느껴지는 힐링 송." },
  { title: "선물", artist: "멜로망스 (MeloMance)", mood: "평온", genre: "Ballad", lang: "ko", youtubeId: "qYYJqWsBb1U", desc: "평범한 일상이 선물처럼 느껴지게 만드는 곡." },
  { title: "오래된 노래", artist: "스탠딩 에그 (Standing Egg)", mood: "평온", genre: "Folk", lang: "ko", youtubeId: "bW3XExLBf7A", desc: "편안하고 잔잔하게 추억을 떠올리는 노래." },
  { title: "마리골드 (マリーゴールド)", artist: "아이묭 (Aimyon)", mood: "평온", genre: "J-Pop", lang: "ja", youtubeId: "0xSiBpUdW4E", desc: "따뜻하고 아련한 감성의 일본 히트곡." },
  { title: "스파클 (スパークル)", artist: "RADWIMPS", mood: "평온", genre: "J-Pop", lang: "ja", youtubeId: "_KoB4onMgQk", desc: "너의 이름은 OST, 별이 쏟아지는 듯한 아름다운 곡." },

  // =====================
  // 4. 분노 (Anger) - 스트레스 풀리는 강렬한 25곡
  // =====================
  { title: "불타오르네 (FIRE)", artist: "BTS", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "ALj5MKjy2BU", desc: "모든 것을 불태워버릴 듯한 폭발적인 에너지." },
  { title: "MIC Drop", artist: "BTS", mood: "분노", genre: "Hip-hop", lang: "ko", youtubeId: "kTlv5_Bs8aw", desc: "헤이터들에게 날리는 통쾌한 힙합 비트." },
  { title: "Believer", artist: "Imagine Dragons", mood: "분노", genre: "Rock", lang: "en", youtubeId: "7wtfhZwyrcc", desc: "고통을 힘으로 바꾸는 강력한 드럼 비트." },
  { title: "In The End", artist: "Linkin Park", mood: "분노", genre: "Rock", lang: "en", youtubeId: "eVTXPUF4Oz4", desc: "답답한 현실에 소리 지르고 싶을 때 듣는 명곡." },
  { title: "Numb", artist: "Linkin Park", mood: "분노", genre: "Rock", lang: "en", youtubeId: "kXYiU_JCYtU", desc: "억압된 감정을 터뜨리는 락의 전설." },
  { title: "It's My Life", artist: "Bon Jovi", mood: "분노", genre: "Rock", lang: "en", youtubeId: "vx2u5uUu3DE", desc: "내 인생은 나의 것, 주먹 쥐고 부르는 노래." },
  { title: "Lose Yourself", artist: "Eminem", mood: "분노", genre: "Hip-hop", lang: "en", youtubeId: "_Yhyp-_hX2s", desc: "비장한 각오와 에너지를 주는 힙합 명곡." },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", mood: "분노", genre: "Rock", lang: "en", youtubeId: "hTWKbfoikeg", desc: "90년대 록의 아이콘, 반항적인 에너지의 절정." },
  { title: "Kill This Love", artist: "BLACKPINK", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "2S24-y0Ij3Y", desc: "강렬한 브라스 사운드가 돋보이는 걸크러쉬 곡." },
  { title: "내가 제일 잘 나가", artist: "2NE1", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "j7_lSP8Vc3o", desc: "자신감으로 무장하고 싶을 때 듣는 최고의 곡." },
  { title: "Bang Bang Bang", artist: "BIGBANG", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "2ips2mM7Zqw", desc: "스트레스를 날려버리는 강렬한 파티 앤섬." },
  { title: "삐딱하게", artist: "G-DRAGON", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "RKhsHGfrFmY", desc: "다 집어치우고 삐뚤어지고 싶은 날 듣는 곡." },
  { title: "싫어 (Hate)", artist: "4MINUTE", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "D_F9HUTYnl0", desc: "싫어! 라고 외치며 이별을 고하는 강렬한 댄스곡." },
  { title: "Very Good", artist: "블락비 (Block B)", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "kJGcO5Une-g", desc: "미친 듯이 놀고 싶을 때 듣는 악동들의 노래." },
  { title: "신메뉴", artist: "Stray Kids", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "TQTlCHxyuu8", desc: "강렬하고 중독성 있는 마라맛 비트." },
  { title: "Wonderland", artist: "ATEEZ", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "Z_BhMhZpAug", desc: "행진곡처럼 웅장하고 파워풀한 퍼포먼스 곡." },
  { title: "Monster", artist: "EXO", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "KSH-FVVtTf0", desc: "어둡고 강렬한 비트가 심장을 울리는 곡." },
  { title: "Scream", artist: "Dreamcatcher", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "FKlGHHhTOsQ", desc: "록 사운드와 아이돌의 결합, 비명 지르고 싶은 곡." },
  { title: "Tomboy", artist: "(여자)아이들", mood: "분노", genre: "K-Pop", lang: "ko", youtubeId: "Jh4QFaPmdss", desc: "편견을 깨부수는 거침없고 락 시크한 곡." },
  { title: "눈누난나", artist: "제시 (Jessi)", mood: "분노", genre: "Hip-hop", lang: "ko", youtubeId: "tJQaUW36pMw", desc: "남들 시선 신경 안 쓰고 내 갈 길 가는 힙한 곡." },
  { title: "시끄러워 (うっせぇわ)", artist: "Ado", mood: "분노", genre: "J-Pop", lang: "ja", youtubeId: "Qp3b-RXtz4w", desc: "사회에 대한 불만을 시원하게 쏟아내는 곡." },
  { title: "홍련화 (紅蓮華)", artist: "LiSA", mood: "분노", genre: "J-Pop", lang: "ja", youtubeId: "CwkzK-F0Y00", desc: "역경을 뚫고 나가는 강렬한 애니메이션 오프닝." },
  { title: "The Beginning", artist: "ONE OK ROCK", mood: "분노", genre: "Rock", lang: "ja", youtubeId: "Hh9yZWeTmVM", desc: "달리기 할 때 들으면 좋은 질주감 넘치는 락." },
  { title: "Girlfriend", artist: "Avril Lavigne", mood: "분노", genre: "Rock", lang: "en", youtubeId: "Bg59q4puhmg", desc: "신나는 팝 펑크 사운드로 에너지를 충전." },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", mood: "분노", genre: "Pop", lang: "en", youtubeId: "R7UrFYvl5TE", desc: "이별 후의 해방감을 속 시원하게 외치는 곡." }
];